server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: task-tracker
          uri: lb://TASK-TRACKER
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/catalizator
    username: postgres
    password: 123
  flyway:
    url: jdbc:postgresql://postgres:5432/catalizator
    user: postgres
    password: 123
jwt:
  secret: very-very-secret-key-should-be-almost-infinity
  expiration: 86400
