server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: secureService
          uri: lb://SECURED-SERVICE
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}

